### ISSUE TITLE
Freezing and lagging

### ISSUE THREAD

**Issue by samusmclame** [Unity-Technologies/facial-ar-remote#19] opened 2018-12-12 03:52 UTC
it appears that the program lags when in use. at first, it's completely fine, but as time goes on it freezes more and more. it could be heat related but i believe it might also be something in the code. if this is a known issue is there any documentation on it?

**Comment by samusmclame** [comment] 2018-12-23 00:32
so apparently this was a known issue regarding not compiling on version 2018? but i did and i still get it?

**Comment by mtschoen-unity** [comment] 2018-12-25 21:40
Hm... I think this is the behavior that I was describing... I only found it to happen once per run of the app in my experience, and it was completely resolved in 2018.2. That said, this was earlier this year, so the latest 2018.2.20 might have re-introduced the regression. I'll try out a build with the latest version and see what happens.

**Comment by samusmclame** [comment] 2018-12-26 04:53
perhaps, i did build it on 2018 2.5 I believe due let me know what you find!

**Comment by samusmclame** [comment] 2018-12-27 19:57
After rebuilding on 2018.2.2 i still find that the iPhone app itself freezes every so often, even before the phone is warm. it then continues afterward. but these pauses are frequent and long if you have a working build could you please pass it on so i can see what's going on? i'm not sure why i'm getting this still

**Comment by mtschoen-unity** [comment] 2019-01-03 21:41
Hi there! I've finally had a chance to investigate this issue, but haven't been able to reliably reproduce the problem. I _did_ end up seeing some lagging in the phone app in release mod without it attached to XCode, but as soon as I made a new development build and tried to catch those frames with the profiler or log viewer, I was unable to reproduce the issue.

Do you have a procedure that produces the problem consistently? Could you provide some more information about your setup? What phone are you using, and what version of iOS is it running? Do you have the latest versions of this project and the ARKit Plugin from bitbucket? Are you using custom content, or just trying the example project? Does the same issue occur when building the Sloth example directly out of the ARKit plugin project?

Thanks for reporting, and hopefully we can get to the bottom of this issue.

**Comment by lesleyklassen** [comment] 2019-01-19 00:09
@samusmclame, I am eagerly following this thread.  I hope you get a chance to follow up on @mtschoen's questions.

**Comment by samusmclame** [comment] 2019-01-19 00:36
sorry for the delay. so it appears I'm just a dumb dumb. this problem does indeed only happen in arkit 1.5 when made with the latest this problem doesn't happen, but I was not setting the scene with the character to 2,0 in its settings. making the connection bug out. might want to add documentation stating that when using arkit 2.0 you have to change the settings on the unity client as well.

**Comment by lesleyklassen** [comment] 2019-01-19 23:39
Thanks for that.

**Comment by mtschoen-unity** [comment] 2019-01-20 00:07
Hey @samusmclame. It sounds like the problem is resolved?

To be clear, which setting are you referring to? Is it the `Stream Settings` field on the `Client` component, or the `ARKIT_2_0` scripting define? Both should be set if you are deploying to a phone with iOS 12 and above.

**Comment by mtschoen-unity** [comment] 2019-02-20 02:40
@samusmclame can you let us know if you are still having this issue?

**Comment by samusmclame** [comment] 2019-04-03 11:58
> @samusmclame can you let us know if you are still having this issue?

Sorry for the late reply everyone, Was finishing up my final papers for school. anyhow it was in the stream settings when actually running it.

**Comment by mtschoen-unity** [comment] 2019-04-03 15:33
So it sounds like this issue is resolved, then? I will close out the ticket. Feel free to re-open it if you're still having problems.

**Closed by mtschoen-unity** 2019-04-03 15:33 UTC
